# Generated by Django 5.2 on 2025-05-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_avatar_user_country_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_user", "Can view user"),
                    ("can_block_user", "Can block user"),
                ],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
