# Generated by Django 5.2 on 2025-04-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing",
            "0003_rename_last_attempt_time_mailingattempt_last_attempt_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="title",
            field=models.CharField(max_length=100, verbose_name="название рассылки"),
        ),
    ]
