# Generated by Django 5.2 on 2025-04-29 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_sending",
            field=models.DateTimeField(
                default=datetime.date.today, verbose_name="дата окончания рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_sending",
            field=models.DateTimeField(
                default=datetime.date.today, verbose_name="дата начала рассылки"
            ),
        ),
    ]
