# Generated by Django 5.2 on 2025-04-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailing_end_sending_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("started", "запущена"),
                    ("finished", "закончена"),
                ],
                default="created",
                verbose_name="статус",
            ),
        ),
    ]
