# Generated by Django 5.2 on 2025-04-30 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_mailing_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="message",
        ),
        migrations.AddField(
            model_name="message",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.mailing",
                verbose_name="рассылка",
            ),
        ),
    ]
