# Generated by Django 5.2 on 2025-04-30 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_remove_mailing_message_message_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.mailing",
                verbose_name="рассылка",
            ),
        ),
    ]
