# Generated by Django 5.2 on 2025-04-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_message_mailing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="author",
        ),
    ]
