# Generated by Django 5.2 on 2025-05-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_remove_message_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_deactivate_mailing", "Can deactivate mailing")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
